# This is a basic workflow to help you get started with Actions

name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
 
  build:
    runs-on: ubuntu-latest

      
     
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
             chmod +x ./build.sh
             apt-get install build-essential
             ./build.sh

      - name: checking dirs
        run: ls
