name: macOS build

on:
  workflow_dispatch
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Set up build environment
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '10.3.0'
         
       

      - name: Set up build environment
        uses: actions/checkout@v2

      - name: building
        run: | 
              chmod +x ./build.sh
              ./build.sh
          
            
     
      
      - name: checking directories
        run: ls
